# Generated by Django 5.0.1 on 2024-01-24 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, max_length=400, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('record_version', models.IntegerField(blank=True, default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dadge',
            },
        ),
        migrations.CreateModel(
            name='BadgeUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('new_value', models.CharField(max_length=400)),
                ('old_value', models.CharField(max_length=400)),
                ('authorized', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now=True)),
                ('authorized_at', models.DateTimeField(null=True)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge.badge')),
            ],
            options={
                'db_table': 'badge_update_request',
            },
        ),
    ]
