# Generated by Django 5.0.1 on 2024-01-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeupdaterequest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
