# Generated by Django 5.0.1 on 2024-01-26 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_badgeupdaterequest_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='badge',
            table='badge',
        ),
    ]
